{{
    config(
        materialized = 'incremental',
        tags = ['gscv_oti_s26_dcreceipts_grandmaster','gscv_oti_s26_150_arthur_dly_dc_rcpt_child'],
        alias = 'gscv_dly_dc_rcpt_lookup_rejects_appended',
        post_hook=["{% do reusable_js_s3_redshift_copy_withdynamicschema_new_api(this.schema,'rmdw_stge' ,'oti_dc_rcpt_rjct', this.identifier, 1) %}"]
    )
}}

SELECT 
  oti_dc_rcpt_rjct_id,
  err_cd,
  item_number,
  wsi,
  dc,
  countrycode,
  transdc,
  CAST(daterc AS DATE) AS daterc,
  cases,
  fcacost,
  fcacurr,
  freedc,
  freedccurr,
  poline,
  ponum,
  CAST(transdate AS DATE) AS transdate,
  localflag,
  gtin,
  transdc_gln,
  facility_gln,
  dc_gln,
  terr_cd,
  srce_file_recv_ts,
  fst_occr_dt,
  ltst_reoc_dt,
  cnt_of_occr_nu,
  CAST(rsol_dt AS TIMESTAMP) AS rsol_dt,
  sevr_typ,
  err_ds,
  cmnt_tx,
  rec_serl_nu,
  srce_file_nm,
  dw_file_id,
  SRCE_ERR_TYP_ID,
  DQ_RSPN_TYP_ID
FROM {{ ref('gscv_dly_dc_rcpt_lookup_rejects_appended_1') }}
UNION ALL
SELECT
  oti_dc_rcpt_rjct_id,
  err_cd,
  item_number,
  wsi,
  dc,
  countrycode,
  transdc,
  CAST(daterc AS DATE) AS daterc,
  cases,
  fcacost,
  fcacurr,
  freedc,
  freedccurr,
  poline,
  ponum,
  CAST(transdate AS DATE) AS transdate,
  localflag,
  gtin,
  transdc_gln,
  facility_gln,
  dc_gln,
  terr_cd,
  srce_file_recv_ts,
  fst_occr_dt,
  ltst_reoc_dt,
  cnt_of_occr_nu,
  CAST(rsol_dt AS TIMESTAMP) AS rsol_dt,
  sevr_typ,
  err_ds,
  cmnt_tx,
  rec_serl_nu,
  srce_file_nm,
  dw_file_id,
  SRCE_ERR_TYP_ID,
  DQ_RSPN_TYP_ID
FROM {{ ref('gscv_dly_dc_rcpt_lookup_rejects_appended_2') }}