version: 2

sources:

  - name: Redshift_gdap_Schema
    project: dmgcp-del-155
    schema: rmdw_tables
    tables:
      - name: std_sld_menu_itm
      - name: std_itm_char_val
      - name: std_itm_char  
      - name: itm_hrcy_lvl_node_asgn
      - name: std_itm_hrcy_node
      - name: std_itm_hrcy_lvl
      - name: std_sld_menu_itm_lkup
      - name: std_itm_hrcy_node_asgn
      - name: std_itm_hrcy_lvl_node_asgn
      - name: mo_trdg_dy_adj
      - name: std_itm_char_vld_list
      - name: gbal_menu_itm

  - name: Redshift_gdap_Stage
    database: dmgcp-del-155
    schema: rmdw_stge
    tables:
      - name: std_sld_menu_itm
      - name: std_itm_hrcy_node_asgn
      - name: std_itm_hrcy_lvl_node_asgn
      - name: stg_std_itm_hrcy_lvl_node_asgn
      - name: itm_hrcy_node
      
  - name: rmdw_stge
    database: dmgcp-del-155
    schema: rmdw_stge
    tables:
      - name: std_sld_menu_itm
      - name: std_itm_char_val

  - name: Item_Vista_Schema
    database: dmgcp-del-155
    schema: item_vista
    tables:
      - name: VISTA_Menu_Item_Hrcy_Mstr_IM2
      - name: hrcy_lookup_psv_tFileInputDelimited_2
      - name: hrcy_lookup_psv_tFileInputDelimited_1
      - name: VISTA_Menu_Item_Hrchy_Assn_tFileInputDelimited_3

  - name: MCD_DBT_IV
    database: dmgcp-del-155
    schema: MCD_DBT_IV
    tables:
      - name: schema_compliance_check_menu_item_hrcy_mstr
      - name: VISTA_Menu_Item_Hrcy_Mstr_IM2
      - name: intermediate_vista_menu_item_hrcy_mstr_valid
      - name: vista_menu_item_hrcy_mstr_valid

  - name: MacD_GSCV_data_audit
    database: dmgcp-del-155
    schema: MacD_GSCV_data_audit
    tables:
      - name: oti_dc_raw_itm_invn
      - name: schn_oti_objt_dq_rule_assc

  - name: rmdw_tables
    database: dmgcp-del-155
    schema: rmdw_tables
    tables:
      - name: std_sld_menu_itm
      - name: gbal_menu_itm
      - name: std_itm_hrcy_node_asgn
      - name: std_itm_hrcy_node
      - name: std_itm_char_val
      - name: std_itm_char_vld_list
      - name: im_terr_vers_cnfg
      - name: rest_hrcy_snap
      - name: wk_end_sun
      - name: prmo_itm
      - name: itm_char_val    

  - name: MacD_GSCV_rmdw_tables
    database: dmgcp-del-155
    schema: MacD_GSCV_rmdw_tables
    tables:
      - name: curn
      - name: fcil
      - name: fcil_ad
      - name: raw_itm
      - name: shpg_unt
      - name: supp_fcil
      - name: ctry
      - name: dc_rcpt
      - name: shpg_unt_cat_hrcy_srm

  - name: schema_compliance_check
    project: dmgcp-del-155
    schema: schema_compliance_check
    tables:
      - name: schema_rules      
             